[package]
name = "ray_tracing_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ppm_img"
path = "src/ss_2/ppm_img.rs"

[[bin]]
name = "ppm_img_2"
path = "src/ss_3/ppm_img.rs"

[[bin]]
name = "scene_rays"
path = "src/ss_4/scene_rays.rs"

[dependencies]
